name: Build 32-bit VS Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装最新的 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # 使用明确版本号

      # 设置环境变量并克隆源码
      - name: Prepare Environment
        run: |
          git clone https://github.com/<<your-github-account>>/vscode.git
          cd vscode
          git checkout main
          git pull https://github.com/microsoft/vscode.git main
        env:
          npm_config_msvs_version: '2022' # 设置 MSVS 版本

      # 配置 32 位环境变量并安装依赖
      - name: Install Dependencies for 32-bit
        shell: pwsh
        run: |
          git clean -fdx
          $env:npm_config_arch = 'ia32'
          yarn install
        env:
          npm_config_msvs_version: '2022' # 设置 MSVS 版本

      # 下载 32 位版本的 Electron
      - name: Download 32-bit Electron
        shell: pwsh
        run: |
          yarn electron ia32
        env:
          npm_config_msvs_version: '2022' # 设置 MSVS 版本

      # 构建 32 位 VS Code
      - name: Build VS Code
        shell: pwsh
        run: |
          .\scripts\code.bat
        env:
          npm_config_msvs_version: '2022' # 设置 MSVS 版本

      # 验证版本信息
      - name: Verify Build
        run: |
          .\scripts\code-cli.bat --version
